version: 2.1
executors:
  docker-publisher:
    environment:
      REPO: 738181112533.dkr.ecr.us-east-2.amazonaws.com
      IMAGE: ${REPO}/buy-it-api:latest
      IMAGE_NUM: ${REPO}/buy-it-api:${CIRCLE_BUILD_NUM}
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Run test
          command: mvn clean test
  build:
    resource_class: medium
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Package application
          command: mvn clean package -Dproject.version=1.1.0-${CIRCLE_BUILD_NUM}
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Build Docker image
          command: | 
            docker build -t buy-it-api:latest .
            docker build -t buy-it-api:${CIRCLE_BUILD_NUM} .
      - run:
          name: Publish Docker image
          command: |
            echo ${IMAGE}
            echo ${IMAGE_NUM}
            docker tag buy-it-api:latest ${IMAGE}
            docker tag buy-it-api:${CIRCLE_BUILD_NUM} ${IMAGE_NUM}
            docker push ${IMAGE}
            docker push ${IMAGE_NUM}

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          context: AWS
#      - build:
#          filters:
#            branches:
#              only: master