version: 2.1
executors:
  docker-publisher:
    environment:
      REPO: 738181112533.dkr.ecr.us-east-2.amazonaws.com
      IMAGE: $REPO/buy-it-api:latest
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Run test
          command: mvn clean test
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to the ERC
          command: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPO
      - run:
          name: Build Docker image
          command: docker build -t buy-it-api .
      - run:
          name: Publish Docker image
          command: |
            docker tag buy-it-api:latest $IMAGE
            docker push $IMAGE

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master