version: 2.1
executors:
  docker-publisher:
    environment:
      REPO: 738181112533.dkr.ecr.us-east-2.amazonaws.com
      IMAGE: $REPO/buy-it-api:latest
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Run test
          command: mvn clean test
  build:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Package application
          command: mvn clean package -Dproject.version=1.1.0-${CIRCLE_BUILD_NUM}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to the ERC
          command: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO
      - run:
          name: Build Docker image
          command: docker build -t buy-it-api .
      - run:
          name: Publish Docker image
          command: |
            docker tag buy-it-api:latest $IMAGE
            docker push $IMAGE

workflows:
  version: 2
  build:
    jobs:
      - test
      - build
#      - build:
#          filters:
#            branches:
#              only: master