version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Run test
          command: mvn clean test
  build:
    environment:
      IMAGE: 738181112533.dkr.ecr.us-east-2.amazonaws.com/buy-it-api
    resource_class: medium
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Package application
          command: mvn clean package -Dproject.version=1.0.0-${CIRCLE_BUILD_NUM}
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Login to ECR
          command: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 738181112533.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: Build Docker image
          command: | 
            docker build -t buy-it-api:latest .
            docker build -t buy-it-api:${CIRCLE_BUILD_NUM} .
      - run:
          name: Publish Docker image
          command: |
            docker tag buy-it-api:latest ${IMAGE}:latest
            docker tag buy-it-api:${CIRCLE_BUILD_NUM} ${IMAGE}:${CIRCLE_BUILD_NUM}
            docker push ${IMAGE}:latest
            docker push ${IMAGE}:${CIRCLE_BUILD_NUM}
      - run:
          name: Success build notify
          command: ./tools/notify.sh success 'Buy IT API'
          when: on_success
      - run:
          name: Failed build notify
          command: ./tools/notify.sh failed 'Buy IT API'
          when: on_fail

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          context: AWS
          filters:
            branches:
              only: master